name: Test
on: [push]
jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get
      - name: Test
        run: go test ./...
